# Basics

# numpy ref https://numpy.org/doc/stable/reference/index.html

In [1]:
import numpy as np

# creat array and all uses of numpy through call of np.
first_array = np.array([1, 2, 3])
print(first_array)

# Remember 2d structure is a concept, first row is 0, but first value is also 0, as a col is just an element in a row. Each index of a row makes a conceptual col.
two_d_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

print(two_d_array)
for i in range(len(two_d_array)):
    for j in range(3):
        print(two_d_array[i][j])

# get dimension of or shape(vector) of array
two_d_array.ndim
two_d_array.shape


[1 2 3]
[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


(2, 3)

# Accessesing and changing elements, row, cols etc.

In [49]:
two_d_array = np.array([[1, 2, 3, 4, 5,], [6, 7, 8, 9, 10,]])
# access specific element i.e 5
ele =two_d_array[1,1]
 # get specific row i, second row. use list slice syntax :
row = two_d_array[1:]
print(row)
# for section of a row, ie row from second element to fourth element, remember will extracat from first arg, but one before last arg.
row_two = two_d_array[0, 1:4]
print(row_two)

# get spec col i.e second col
col = two_d_array[:, 1]
print(col)

#  stepsze extraction, every other one except

step_row = two_d_array[0, 1:6:2]
print(step_row)

# change element change using index arguments. i.e change first element to 20

two_d_array[0, 0] = 12
print(two_d_array[0, :])

# initialise with random numbers

rando = np.random.rand(3,3)
print(rando)


[[ 6  7  8  9 10]]
[2 3 4]
[2 7]
[2 4]
[12  2  3  4  5]
[[0.2402654  0.4565271  0.86081201]
 [0.2381365  0.01798055 0.18432569]
 [0.63212667 0.51129787 0.19137409]]


# Initialize arrays

In [47]:
zero_two_d =np.zeros((2, 2))

one_three_d = np.ones((3, 3, 3))

print(zero_two_d)
print(one_three_d)





[[0. 0.]
 [0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# mathematics


In [51]:
# additon to elements
a = np.array([1, 2, 3, 4])

a + 2

array([3, 4, 5, 6])

In [ ]:
# multiplication to elements
a = np.array([1, 2, 3, 4])

a * 2

In [52]:
# division of elements
a = np.array([1, 2, 3, 4])
a / 2


array([0.5, 1. , 1.5, 2. ])

In [53]:
# subtraction to elements
a = np.array([1, 2, 3, 4])

a - 2

array([-1,  0,  1,  2])

In [54]:
# additon of two arrays of elements
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a + b
# loads of maths routines incuding trig, exponentials, hyperbolics etc at link.

array([3, 5, 7, 9])

In [71]:
# summation of array
a = np.array([1, 2, 3, 4])
cum_sum = np.sum(a)
print(cum_sum)

# cumsum appends cumaltive total

a_cumsum = np.cumsum(a)
print(a_cumsum)

# total product
tot_prod = np.prod(a)
print(tot_prod)
# cum prod appends product to array

cum_prod = np.cumprod(a)
print(cum_prod)

10
[ 1  3  6 10]
24
[ 1  2  6 24]


# maths function https://numpy.org/doc/stable/reference/routines.math.html

# maths linear algebra

In [55]:
# matrix multiplication, produces 2x2 matrix
a = np.ones((2, 3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [59]:
# find derterminate, make c identity matrix. Then calc determinate which is 1. can be done for any matrix.
c = np.identity(2)
print(c)
determinant = np.linalg.det(c)
print(determinant)

# loads of vector and matrix functions such as vector product, invert matrix, eigenvalues etc at link below.

[[1. 0.]
 [0. 1.]]
1.0


# linalg functions and routines https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1FfeEtqMmpzd1lnNVVIbWMxcWM2ZTdVN2xyZ3xBQ3Jtc0trS0FDdUZ3eEVUWDhQWmNNZE9XTWlpUzNfT3lsQXA4blBialdWRExFYU5OWXNGbTVXci1oQmxhVHFVVUJvZGhyaFVuSEVLVHZ2M25fd3ZsSWRBSHp2UG9RenRuSE9QeFFoZmhuaXlHb1Z2OVpEQ19Idw&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.linalg.html&v=QUT1VHiLmmI

# Stats TBD

# Reorg, vstack and hstack.

In [62]:
#change shape of multi d array ie from (3, 2) to (2,3)

before = np.array([[1, 2, 3], [4, 5, 6]])
print(before)
 # first arg number of rows, second arg number of cols(or elements in a row)
after = before.reshape((3, 2))
print(after)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [73]:
# vertical stacking vectors
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

v_stack = np.vstack([a, b, a, b])
print(v_stack)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [74]:
# horizontal stacking
a = np.zeros((2, 2))
b =np.ones((2,2))

h_stack = np.hstack((a, b))
print(h_stack)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


# data from file  TBD

# Advanced indexing and Boolean masking

In [79]:
# use an operator to find boolean value in arrar. i.e where value is greater than 20
a = np.array([[23, 32, 11, 15], [44, 67, 23, 13,], [9, 56, 34, 22]])

a > 20


array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [False,  True,  True,  True]])

In [80]:
# create a new array based on parameters. this extracts all values within boundary and appends to new array. 
# ie where element is less than 25.

b = a[a < 25]

print(b)

[23 11 15 23 13  9 22]


In [81]:
# index an array with a list. extracts indexs and appends to list.
a = np.array([23, 32, 11, 15, 44, 67, 23, 13, 9, 56, 34, 22])

b = a[[3, 4, 7]]

print(b)

[15 44 13]


In [88]:
# check values in all col using axis ie 0 all values on the axis 0 for col and axis 1 for rows
a = np.array([[23, 32, 11, 15], [44, 67, 23, 13,], [9, 56, 34, 22]])
print(a)
np.any(a < 13, axis=0)

[[23 32 11 15]
 [44 67 23 13]
 [ 9 56 34 22]]


array([ True, False,  True, False])